modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/MPThLee/DisableComplianceNotification/issues"
license = "MIT"

[[mods]]
modId = "disable_compliance_notification"
version = "${version}-${minecraft_version}-forge"
displayName = "Disable Compliance Notification"
authors = "MPThLee"
description = '''
Disable Compliance Notification for South Korean users.
'''
#logoFile = ""

[[dependencies.disable_compliance_notification]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.disable_compliance_notification]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.disable_compliance_notification]]
modId = "architectury"
mandatory = true
versionRange = "[4.5.76,)"
ordering = "AFTER"
side = "BOTH"