# Common config
archives_base_name=disable_compliance_notification
maven_group=dev.mpthlee.minecraft.disable_compliance_notification


### VERSION ###
## BASE VERSION ##
# Java
java_version=25

# Mod and Minecraft
mod_version=1.5.6
minecraft_version=26.1
pack_format=84.0

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=62.0.9

# NeoForge
# https://neoforged.net/
neoforge_version=26.1.0.1-beta

# Fabric
# https://fabricmc.net/develop/
fabric_loader_version=0.18.6
fabric_api_version=0.145.1

## BUILD TOOL ##
# Mixin specific
mixin_processor_version=0.8.7
fabric_mixin_processor_version=0.17.1


## DEPENDENCIES ##
# YACL (Yet Another Config Lib)
yacl_version=3.9.1+26.1

# Mod Menu
modmenu_version=18.0.0-alpha.8
