# Common config
archives_base_name=disable_compliance_notification
maven_group=dev.mpthlee.minecraft.disable_compliance_notification


### VERSION ###
## BASE VERSION ##
# Java
java_version=25

# Mod and Minecraft
mod_version=1.5.9
minecraft_version=26.2
pack_format=88.0

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=65.0.0

# NeoForge
# https://neoforged.net/
neoforge_version=20.2.12-beta

# Fabric
# https://fabricmc.net/develop/
fabric_loader_version=0.19.3
fabric_api_version=0.145.4

## BUILD TOOL ##
# Mixin specific
mixin_processor_version=0.8.7
fabric_mixin_processor_version=0.17.1


## DEPENDENCIES ##
# YACL (Yet Another Config Lib)
yacl_version=3.9.4+26.2

# Mod Menu
modmenu_version=20.0.0-beta.2
