modLoader = "javafml"
#loaderVersion = "[${neoforge_major_version},)"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/MPThLee/DisableComplianceNotification/issues"
license = "MIT"

[[mods]]
modId = "disable_compliance_notification"
version = "${version}"
displayName = "Disable Compliance Notification"
authors = "MPThLee"
description = '''
Disable Compliance Notification for South Korean users.
'''
logoFile="assets/disable_compliance_notification/icon.png"

[[dependencies.disable_compliance_notification]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_major_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.disable_compliance_notification]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.disable_compliance_notification]]
modId = "cloth_config"
type = "optional"
versionRange = "[${cloth_config_major_version},)"
ordering = "NONE"
side = "CLIENT"
[dependencies.disable_compliance_notification.mc-publish]
ignore=false
modrinth="cloth-config"
curseforge="cloth-config"

[[mixins]]
config="disable_compliance_notification.mixins.json"