modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
issueTrackerURL = "https://github.com/MPThLee/DisableComplianceNotification/issues"
license = "MIT"

[[mods]]
modId = "disable_compliance_notification"
version = "${version}"
displayName = "Disable Compliance Notification"
authors = "MPThLee"
description = '''
Disable Compliance Notification for South Korean users.
'''
#logoFile = ""

[[dependencies.disable_compliance_notification]]
modId = "forge"
mandatory = true
versionRange = "[${forge_major_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.disable_compliance_notification]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.disable_compliance_notification]]
modId = "cloth_config"
mandatory = false
versionRange = "[${cloth_config_major_version,)"
ordering = "NONE"
side = "CLIENT"