name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        loader: [ 'forge', 'fabric' ]
        java: [ 17 ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          distribution: 'microsoft'
          java-version: ${{ matrix.java }}

      - name: Set up swap space
        if: runner.os == 'Linux'
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10

      - name: Build with ${{ matrix.loader }}
        run: |
          cd ${{ matrix.loader }}
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload ${{ matrix.loader }} build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.loader }}-artifact
          path: ${{ matrix.loader }}/build/libs

  release:
    runs-on: ubuntu-latest

    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download forge artifact
        uses: actions/download-artifact@v3
        with:
          name: forge-artifact

      - name: Download fabric artifact
        uses: actions/download-artifact@v3
        with:
          name: fabric-artifact

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.jar
