name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew build

      - name: Upload forge build artifact
        uses: actions/upload-artifact@v2
        with:
          name: forge-artifact
          path: forge/build/libs

      - name: Upload fabric build artifact
        uses: actions/upload-artifact@v2
        with:
          name: fabric-artifact
          path: fabric/build/libs

      - name: Upload quilt build artifact
        uses: actions/upload-artifact@v2
        with:
          name: quilt-artifact
          path: quilt/build/libs
      
      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: chmod +x ./tools/make-release.sh $$ ./tools/make-release.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            release/*/*.jar