name: Build

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        loader: [ 'forge', 'fabric' ]
        java: [ 17 ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: ${{ matrix.java }}

      - name: Set up swap space
        if: runner.os == 'Linux'
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10

      - name: Build with ${{ matrix.loader }}
        run: |
          cd ${{ matrix.loader }}
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload ${{ matrix.loader }} build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.loader }}-artifact
          path: ${{ matrix.loader }}/build/libs

  release:
    runs-on: ubuntu-latest

    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download forge artifact
        uses: actions/download-artifact@v3
        with:
          name: forge-artifact

      - name: Download fabric artifact
        uses: actions/download-artifact@v3
        with:
          name: fabric-artifact

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.jar

  publish:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        loader: [ 'forge', 'fabric' ]

    steps:
      - name: checkout repository for data
        uses: actions/checkout@v3
        with:
          path: 'repo'
      - name: Set variables that required to publish
        id: variables
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const loader = '${{ matrix.loader }}';
            const propFile = fs.readFileSync("repo/config.properties", { encoding: "UTF-8", flag: "r" });
            const prop = propFile
                          .split("\n")
                          .map((s) => { s = s.trim(); return s.startsWith("#") ? "" : s; })
                          .filter(s => s !== '')
                          .reduce((a, c) => { let [k, v] = c.split("=").map(s => s.trim()); return { ...a, [k]: v }; }, {});

            core.setOutput('capital_loader', loader.charAt(0).toUpperCase() + loader.slice(1)); 
            core.setOutput('full_version', `${prop.mod_version}+${loader}-${prop.minecraft_version}`);
            for (const [key, value] of Object.entries(prop)) {
              core.setOutput(`prop_${key}`, value);
            }

      - name: Download ${{ matrix.loader }} artifact
        uses: actions/download-artifact@v3
        with:
          path: ${{ matrix.loader }}
          name: ${{ matrix.loader }}-artifact

      - name: Upload ${{ matrix.loader }} version to CurseForge and Modrinth
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: vAYtksKy
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 644324
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files-primary: ${{ matrix.loader }}/!(*-@(dev|sources|javadoc)).jar
          files-secondary: ${{ matrix.loader }}/*-@(dev|sources|javadoc).jar

          name: '[${{ steps.variables.outputs.capital_loader }} ${{ steps.variables.outputs.prop_minecraft_version }}] ${{ steps.variables.outputs.prop_mod_version }}'
          version: ${{ steps.variables.outputs.full_version }}
          game-versions: ${{ steps.variables.outputs.prop_minecraft_version }}
          loaders: ${{ matrix.loader }}
